config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views import defaults as default_views

urlpatterns = [
    path('', include('questionbank.dashboards.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('questionbank.users.urls')),
    path('invites/', include('questionbank.invites.urls')),
    path('subjects/', include('questionbank.subjects.urls')),
    path('questions/', include('questionbank.questions.urls')),
    path('exams/', include('questionbank.exams.urls')),
    path('comments/', include('questionbank.comments.urls')),
    path('analysis/', include('questionbank.analyses.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += [
        path(
            '400/', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]

questionbank/comments/urls.py
from django.urls import path

from .views import (
    ExamCommentListView, ExamCommentCreateView, ExamCommentUpdateView,
    ExamCommentDeleteView, ExamCommentResolveView, QuestionCommentListView,
    QuestionCommentCreateView, QuestionCommentUpdateView,
    QuestionCommentDeleteView, QuestionCommentResolveView
)

app_name = 'comments'
urlpatterns = [
    path('exams/<int:exam_id>/', ExamCommentListView.as_view(), name='exam_list'),
    path(
        'exams/<int:exam_id>/create/',
        ExamCommentCreateView.as_view(),
        name='exam_create'
    ),
    path(
        'exams/<int:exam_id>/update/<int:pk>/',
        ExamCommentUpdateView.as_view(),
        name='exam_update'
    ),
    path(
        'exams/<int:exam_id>/delete/<int:pk>/',
        ExamCommentDeleteView.as_view(),
        name='exam_delete'
    ),
    path(
        'exams/<int:exam_id>/resolve/<int:pk>/',
        ExamCommentResolveView.as_view(),
        name='exam_resolve'
    ),

    path(
        'questions/<int:question_id>/',
        QuestionCommentListView.as_view(),
        name='question_list'
    ),
    path(
        'questions/<int:question_id>/create/',
        QuestionCommentCreateView.as_view(),
        name='question_create'
    ),
    path(
        'questions/<int:question_id>/update/<int:pk>/',
        QuestionCommentUpdateView.as_view(),
        name='question_update'
    ),
    path(
        'questions/<int:question_id>/delete/<int:pk>/',
        QuestionCommentDeleteView.as_view(),
        name='question_delete'
    ),
    path(
        'questions/<int:question_id>/resolve/<int:pk>/',
        QuestionCommentResolveView.as_view(),
        name='question_resolve'
    )
]

questionbank/exams/urls.py
from django.urls import path

from .views import (
    ExamListView, ExamCreateView, ExamUpdateView, ExamQuestionView,
    ExamDeleteView, ExamPrintView
)


app_name = 'exams'
urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('create/', ExamCreateView.as_view(), name='create'),
    path('<int:pk>/update/', ExamUpdateView.as_view(), name='update'),
    path('<int:pk>/add-question/', ExamQuestionView.as_view(), name='add_question'),
    path('<int:pk>/delete/', ExamDeleteView.as_view(), name='delete'),
    path('<int:pk>/print/', ExamPrintView.as_view(), name='print')
]

questionbank/subjects/urls.py
from django.urls import path

from .views import (
    SubjectListView, SubjectCreateView, SubjectUpdateView, SubjectDeleteView
)

app_name = 'subjects'
urlpatterns = [
    path('', SubjectListView.as_view(), name='list'),
    path('create/', SubjectCreateView.as_view(), name='create'),
    path('<int:pk>/update/', SubjectUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', SubjectDeleteView.as_view(), name='delete')
]

questionbank/exams/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from ckeditor_uploader.fields import RichTextUploadingField

from questionbank.questions.models import Question
from questionbank.subjects.models import Subject

User = get_user_model()


class Exam(models.Model):
    name = models.CharField(max_length=250)
    session = models.CharField(max_length=255)
    is_published = models.BooleanField(default=False)
    course = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
    exam = RichTextUploadingField(blank=True)  # the exam question and choices
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='exams'
    )
    created_at = models.DateTimeField(auto_now=True)
    questions = models.ManyToManyField(Question, related_name='exam')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('exams:update', kwargs={'pk': self.pk})

questionbank/exams/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget

from questionbank.questions.models import Question
from questionbank.subjects.models import Subject

from .models import Exam
from .widgets import CheckboxSelectMultiple


class ExamForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        coordninator = kwargs.pop('coordinator', None)

        super().__init__(*args, **kwargs)

        if coordninator:
            self.fields['course'].queryset = Subject.objects.filter(name=coordninator.course.name)

    class Meta:
        model = Exam
        fields = ['name', 'session', 'course']


class ExamQuestionForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.course = kwargs.pop('course')
        super().__init__(*args, **kwargs)
        self.fields['questions'].required = False
        self.fields['questions'].queryset = Question.objects.filter(
            course=self.course
        ).order_by('-created_at')

    class Meta:
        model = Exam
        fields = ['questions']
        widgets = {
            'questions': CheckboxSelectMultiple()
        }


class ExamPrintForm(forms.ModelForm):

    class Meta:
        model = Exam
        fields = ['exam', 'is_published']
        widgets = {
            'exam': forms.CharField(widget=CKEditorWidget())
        }
        labels = {
            'is_published': 'Ready to publish'
        }

questionbank/exams/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.utils.html import mark_safe
from django_filters.views import FilterView

from questionbank.users.constants import COORDINATOR

from .models import Exam
from .filters import ExamFilter
from .forms import ExamQuestionForm, ExamPrintForm, ExamForm
from .constants import ALPHABET_MAPPING
from .mixins import LimitedExamMixin


class ExamListView(PermissionRequiredMixin, LimitedExamMixin, FilterView):
    permission_required = 'exams.view_exam'
    model = Exam
    filterset_class = ExamFilter
    template_name_suffix = '_list'
    paginate_by = 20


class ExamCreateView(PermissionRequiredMixin, SuccessMessageMixin, LimitedExamMixin,
                     CreateView):
    permission_required = 'exams.add_exam'
    model = Exam
    form_class = ExamForm
    success_message = '%(name)s Created'

    def get_form_kwargs(self):
        kwarg = super().get_form_kwargs()
        if self.request.user.role == COORDINATOR:
            kwarg['coordinator'] = self.request.user
        return kwarg

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        if 'next' in self.request.POST:
            return reverse('exams:add_question', kwargs={'pk': self.object.pk})
        return reverse('exams:list')


class ExamUpdateView(PermissionRequiredMixin, SuccessMessageMixin, LimitedExamMixin,
                     UpdateView):
    permission_required = 'exams.change_exam'
    model = Exam
    success_url = reverse_lazy('exams:list')
    form_class = ExamForm
    success_message = '%(name)s Updated'

    def get_form_kwargs(self):
        kwarg = super().get_form_kwargs()
        if self.request.user.role == COORDINATOR:
            kwarg['coordinator'] = self.request.user
        return kwarg

    def get_queryset(self):
        return Exam.objects.all().prefetch_related(
            'questions',
            'questions__choices',
            'questions__comments'
        )


class ExamQuestionView(PermissionRequiredMixin, LimitedExamMixin, UpdateView):
    permission_required = 'exams.change_exam'
    model = Exam
    template_name = 'exams/exam_question_form.html'
    form_class = ExamQuestionForm
    success_url = reverse_lazy('exams:list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['course'] = self.object.course
        return kwargs


class ExamDeleteView(PermissionRequiredMixin, LimitedExamMixin, DeleteView):
    permission_required = 'exams.delete_question'
    model = Exam
    success_url = reverse_lazy('exams:list')


class ExamPrintView(PermissionRequiredMixin, LimitedExamMixin, UpdateView):
    permission_required = 'exams.add_exam'
    template_name = 'exams/create_exam.html'
    model = Exam
    form_class = ExamPrintForm
    queryset = Exam.objects.prefetch_related('questions', 'questions__choices')

    def get_initial(self):
        is_schema = self.request.GET.get('schema', None)
        counter = 0
        paper = '''
        <style>
            .q-inline p {
                display: inline;
                padding-right: 5px;
            }
            .q-inline p img{
                display: block;
            }
        </style>
        '''

        for question in self.object.questions.order_by('specialty'):
            counter += 1
            paper += f'''
            <div class="q-inline">
                <p> {str(counter)}.</p>
                {question.question}
            </div>
            '''

            inner_counter = 0

            for choice in question.choices.all():
                correct = ''
                if choice.is_correct and is_schema:
                    correct = 'style="color: red"'

                inner_counter += 1
                paper += f'''
                <div class="q-inline" {correct}>
                    <p>{ALPHABET_MAPPING[inner_counter]}.</p>
                    {choice.choice}
                </div>
                '''

        initial = super().get_initial()
        initial['exam'] = mark_safe(paper)
        return initial

    def get_success_url(self):
        return self.object.get_absolute_url()

templates/exams/create_exam.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-12">
      <a href="#" class="btn btn-outline-primary" onclick="window.history.back()">
        <i class="fas fa-angle-left fa-xs"></i>
        Back
      </a>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="Save" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</div>

<script src="//cdn.ckeditor.com/4.11.4/full/ckeditor.js"></script>
<script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
{% endblock content %}

templates/exams/exam_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-6">
    <a href="{% url 'exams:list' %}" class="btn btn-outline-primary">
      <i class="fas fa-angle-left fa-xs"></i>
      Cancel
    </a>
  </div>
  <div class="col-6 text-right">
    {% if object %}
      <!--
      <div class="btn-group">
        <button class="btn btn-warning dropdown-toggle" type="button" data-toggle="dropdown">
          Comments
        </button>
        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 35px, 0px);">
          <a class="dropdown-item" href="{% url 'comments:exam_list' exam.pk %}?is_resolved=false">
              Unresolved comments
              <span class="badge badge-light badge-pill" style="position: static;">
                {{ unresolved_comment }}
              </span>
          </a>
          <a class="dropdown-item" href="{% url 'comments:exam_list' exam.pk %}?is_resolved=unknown">All Comment</a>
          <a class="dropdown-item" href="{% url 'comments:exam_create' exam.pk %}">Create Comment</a>
        </div>
      </div>
      -->
      <a href="{% url 'exams:add_question' exam.pk %}" class="btn btn-outline-primary">
        Update Question
      </a>
      {% if exam.questions.count %}
        <a href="{% url 'exams:print' object.pk %}" class="btn btn-outline-primary">
          Print
        </a>
        <a href="{% url 'exams:print' object.pk %}?schema=1" class="btn btn-outline-primary">
            Print schema
        </a>
      {% endif %}
    {% endif %}
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <i class="nav-icon fas fa-scroll"></i>
        {% if object %}
          <b>Create Exam</b>
        {% else %}
          <b>Exam Form</b>
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="row">
            <div class="col-6">
              <input type="submit" value="Submit" class="btn btn-primary">
              {% if not object.pk %}
                <input type="submit" name="next" value="Add Question >" class="btn btn-outline-primary">
              {% endif %}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% if object %}
  {% for question in exam.questions.all %}
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header text-right">
            <a
              href="{% url 'comments:question_list' question.pk %}?is_resolved=false&exam={{ exam.pk }}"
              class="btn btn-ghost-primary"
              data-toggle="tooltip"
              data-placement="bottom"
              title="View comments"
            >
              <i class="fas fa-comment-dots"></i>
              {{ question.unresolve_comment|default:"" }}
            </a>
            <a
              href="{% url 'comments:question_create' question.pk %}?exam={{ exam.pk }}"
              class="btn btn-ghost-primary"
              data-toggle="tooltip"
              data-placement="bottom"
              title="Create comment"
            >
              <i class="fas fa-comment-medical"></i>
            </a>
          </div>
          <div class="card-body">
            {{ question }}
            {% for choice in question.choices.all %}
              <hr>
              {{ choice }}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
{% endif %}
{% endblock content %}

templates/exams/exam_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-12 text-right">
    <a href="{% url 'exams:create' %}" class="btn btn-outline-primary">
      <i class="fas fa-plus fa-xs"></i>
      Create Exam
    </a>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="card {% if filter.form.errors %}text-white bg-danger{% endif %}">
      <div class="card-header">Filters
        <div class="card-header-actions">
          <a class="card-header-action btn-minimize" href="#" data-toggle="collapse" data-target="#collapseExample">
              <i class="nav-icon fas fa-search-plus"></i>
          </a>
        </div>
      </div>
      <div class="collapse" id="collapseExample">
        <div class="card-body">
          <form method="GET">
            {{ filter.form | crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Search</button>
                <a href="{% url 'subjects:list' %}" class="btn btn-danger">Clear filters</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <i class="nav-icon fas fa-scroll"></i>
        <b>Exam List</b>
      </div>
      <div class="card-body">
        {% if object_list %}
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Session</th>
                <th>Course</th>
                <th>Created By</th>
                <th>Published</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for exam in exam_list %}
              <tr>
                <td>
                  <a href="{% url 'exams:update' exam.pk %}">
                    {{ exam.name }}
                  </a>
                </td>
                <td>{{ exam.session }}</td>
                <td>{{ exam.course }}</td>
                <td>{{ exam.created_by }}</td>
                <td>{{ exam.is_published }}</td>
                <td>
                    <a
                      class="btn btn-outline-danger"
                      href="#"
                      onclick="document.getElementById('delete-{{ forloop.counter }}').submit()"
                    >
                      Delete
                    </a>
                </td>
              </tr>

              <form
                action="{% url 'exams:delete' exam.pk %}"
                id="delete-{{ forloop.counter }}"
                method="post"
                style="display:none"
              >
              {% csrf_token %}
              </form>
              {% endfor %}
            </tbody>
          </table>
        {% else %}
          <div class="clearfix text-center">
            <h4 class="pt-3">No exam found</h4>
            <p class="text-muted">
              You can create one
              <a href="{% url 'exams:create' %}" class="btn-primary">here</a>
            </p>
          </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Previous</a>
      </li>
      {% endif %}

      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1">Next</a>
        </li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Next</a></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}
{% endblock content %}

templates/exams/exam_question_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-12">
      <a href="#" class="btn btn-outline-primary" onclick="window.history.back()">
        <i class="fas fa-angle-left fa-xs"></i>
        Back
      </a>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <i class="nav-icon fas fa-scroll"></i>
        {% if object %}
          <b>Update exam's question</b>
        {% else %}
          <b>Add exam's question</b>
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form }}
          <div class="row">
            <div class="col-12">
              <input type="submit" value="submit" class="btn btn-primary">
              <a href="{% url 'exams:list' %}" class="btn btn-danger">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}