config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views import defaults as default_views

urlpatterns = [
    path('', include('questionbank.dashboards.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('questionbank.users.urls')),
    path('invites/', include('questionbank.invites.urls')),
    path('subjects/', include('questionbank.subjects.urls')),
    path('questions/', include('questionbank.questions.urls')),
    path('exams/', include('questionbank.exams.urls')),
    path('comments/', include('questionbank.comments.urls')),
    path('analysis/', include('questionbank.analyses.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += [
        path(
            '400/', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]

questionbank/analyses/urls.py
from django.urls import path

from .views import AnalysisCreateView, AnalysisUpdateView, AnalysisDeleteView


app_name = 'analyses'
urlpatterns = [
    path(
        '<int:question_id>/create/',
        AnalysisCreateView.as_view(),
        name='create'
    ),
    path(
        '<int:question_id>/update/<int:pk>/',
        AnalysisUpdateView.as_view(),
        name='update'
    ),
    path(
        '<int:question_id>/delete/<int:pk>/',
        AnalysisDeleteView.as_view(),
        name='delete'
    )
]

questionbank/comments/urls.py
from django.urls import path

from .views import (
    ExamCommentListView, ExamCommentCreateView, ExamCommentUpdateView,
    ExamCommentDeleteView, ExamCommentResolveView, QuestionCommentListView,
    QuestionCommentCreateView, QuestionCommentUpdateView,
    QuestionCommentDeleteView, QuestionCommentResolveView
)

app_name = 'comments'
urlpatterns = [
    path('exams/<int:exam_id>/', ExamCommentListView.as_view(), name='exam_list'),
    path(
        'exams/<int:exam_id>/create/',
        ExamCommentCreateView.as_view(),
        name='exam_create'
    ),
    path(
        'exams/<int:exam_id>/update/<int:pk>/',
        ExamCommentUpdateView.as_view(),
        name='exam_update'
    ),
    path(
        'exams/<int:exam_id>/delete/<int:pk>/',
        ExamCommentDeleteView.as_view(),
        name='exam_delete'
    ),
    path(
        'exams/<int:exam_id>/resolve/<int:pk>/',
        ExamCommentResolveView.as_view(),
        name='exam_resolve'
    ),

    path(
        'questions/<int:question_id>/',
        QuestionCommentListView.as_view(),
        name='question_list'
    ),
    path(
        'questions/<int:question_id>/create/',
        QuestionCommentCreateView.as_view(),
        name='question_create'
    ),
    path(
        'questions/<int:question_id>/update/<int:pk>/',
        QuestionCommentUpdateView.as_view(),
        name='question_update'
    ),
    path(
        'questions/<int:question_id>/delete/<int:pk>/',
        QuestionCommentDeleteView.as_view(),
        name='question_delete'
    ),
    path(
        'questions/<int:question_id>/resolve/<int:pk>/',
        QuestionCommentResolveView.as_view(),
        name='question_resolve'
    )
]

questionbank/questions/urls.py
from django.urls import path

from .views import (
    QuestionListView, QuestionCreateView, QuestionUpdateView,
    QuestionDetailView, QuestionDeleteView, ChoiceCreateView,
    ChoiceUpdateView, ChoiceDeleteView
)

app_name = 'questions'
urlpatterns = [
    path('', QuestionListView.as_view(), name='list'),
    path('create/', QuestionCreateView.as_view(), name='create'),
    path('<int:pk>/detail/', QuestionDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', QuestionUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', QuestionDeleteView.as_view(), name='delete'),

    path(
        '<int:question>/choices/create/', ChoiceCreateView.as_view(),
        name='choice_create'
    ),
    path(
        '<int:question>/choices/<int:pk>/update/', ChoiceUpdateView.as_view(),
        name='choice_update'
    ),
    path(
        '<int:question>/choices/<int:pk>/delete/', ChoiceDeleteView.as_view(),
        name='choice_delete'
    )

]

questionbank/users/urls.py
from django.urls import path

from .views import (
    UserListView, UserUpdateView, UserProfileView, UserDeleteView,
    AcceptInvitationView, SpecialtyListView, SpecialtyCreateView, SpecialtyUpdateView,
    SpecialtyDeleteView
)


app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path(
        'invite/<str:token>/', AcceptInvitationView.as_view(),
        name='accept_invite'
    ),
    path('specialties/', SpecialtyListView.as_view(), name='specialty_list'),
    path('specialties/create/', SpecialtyCreateView.as_view(), name='specialty_create'),
    path('specialties/<int:pk>/update/', SpecialtyUpdateView.as_view(), name='specialty_update'),
    path('specialties/<int:pk>/delete/', SpecialtyDeleteView.as_view(), name='specialty_delete')
]

questionbank/questions/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from django.utils.html import mark_safe

from questionbank.subjects.models import Subject
from questionbank.users.models import Specialty

User = get_user_model()


class Question(models.Model):
    question = RichTextUploadingField()
    course = models.ForeignKey(
        Subject, on_delete=models.SET_NULL, null=True, related_name='subjects'
    )
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, related_name='questions'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    specialty = models.ForeignKey(
        to=Specialty, on_delete=models.SET_NULL, null=True, blank=True
    )
    tags = TaggableManager()

    class Meta:
        ordering = ['specialty']

    def __str__(self):
        return mark_safe(self.question)

    def get_absolute_url(self):
        return reverse('questions:detail', kwargs={'pk': self.pk})

    @property
    def unresolve_comment(self):
        return self.comments.filter(is_resolved=False).count()


class Choice(models.Model):
    choice = RichTextUploadingField()
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name='choices'
    )

    class Meta:
        ordering = ['choice']

    def __str__(self):
        return mark_safe(self.choice)

    def get_absolute_url(self):
        return reverse(
            'questions:choice_update',
            kwargs={'pk': self.pk, 'question': self.question.pk}
        )

questionbank/questions/forms.py
from django import forms
from django.forms import inlineformset_factory

from questionbank.exams.models import Exam

from .models import Question, Choice


class QuestionForm(forms.ModelForm):
    exam = forms.ModelChoiceField(
        queryset=Exam.objects.filter(is_published=False).order_by('-created_at'),
        required=False
    )
    field_order = ['exam', 'course', 'question', 'tags']

    class Meta:
        model = Question
        fields = ('course', 'question', 'tags')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tags'].required = False

        if kwargs.get('instance', None) and kwargs['instance'].exam.first():
            self.fields['exam'].initial = kwargs['instance'].exam.first().pk

    def clean(self):
        cleaned_data = super().clean()
        exam = cleaned_data.get('exam', None)
        course = cleaned_data.get('course', None)

        if exam and course:
            if exam.course != course:
                raise forms.ValidationError(
                    "Exam's subject and question subject must be the same"
                )
        return cleaned_data

    def save(self):
        instance = super().save()
        instance.exam.clear()
        if self.cleaned_data['exam']:
            instance.exam.add(self.cleaned_data['exam'])
        return instance


class ChoiceForm(forms.ModelForm):

    class Meta:
        model = Choice
        exclude = ('question',)
        labels = {
            'is_correct': 'Correct choice'
        }


QuestionFormSet = inlineformset_factory(
    Question, Choice, form=ChoiceForm, extra=4, can_delete=False
)

questionbank/questions/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django_filters.views import FilterView

from questionbank.subjects.models import Subject

from .mixins import ChoiceFormMixin, LimitedQuestionMixin
from .filters import QuestionFilter
from .models import Question, Choice
from .forms import QuestionFormSet, QuestionForm


class QuestionListView(PermissionRequiredMixin, LimitedQuestionMixin, FilterView):
    permission_required = 'questions.view_question'
    filterset_class = QuestionFilter
    template_name_suffix = '_list'
    paginate_by = 10
    model = Question
    querset = Question.objects.prefetch_related('exam')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Subject.objects.all()
        return context


class QuestionCreateView(PermissionRequiredMixin, SuccessMessageMixin,
                         LimitedQuestionMixin, CreateView):
    permission_required = 'questions.add_question'
    model = Question
    form_class = QuestionForm
    success_url = reverse_lazy('questions:list')
    success_message = 'Question Created !'
    choice_initial = []

    def get_initial(self):
        """
        create question from another question
        """
        question_id = self.request.GET.get('question', None)

        if question_id:
            # check if the query param exist && valid
            try:
                obj = get_object_or_404(Question, pk=question_id)
            except ValueError:
                raise Http404

            initial = {
                'course': obj.course,
                'question': obj.question,
                'tags': obj.tags.all()
            }

            self.choice_initial = list(
                obj.choices.values('choice', 'is_correct')
            )
            return initial
        return super().get_initial()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['choices'] = QuestionFormSet(initial=self.choice_initial)
        return context

    def post(self, request, *args, **kwargs):
        choices = QuestionFormSet(self.request.POST, self.request.FILES)
        question = self.form_class(self.request.POST, self.request.FILES)
        if choices.is_valid():
            if question.is_valid():
                return self.form_valid(question=question, choices=choices)
        return super(QuestionCreateView, self).post(self.request)

    def form_valid(self, question, choices):
        question.instance.created_by = self.request.user
        q = question.save()

        if self.request.user.specialty:
            q.tags.add(self.request.user.specialty.name)
            q.specialty = self.request.user.specialty
            q.save()

        for choice in choices:
            if choice['choice'].value():
                choice.instance.question = q
                choice.save()
        return HttpResponseRedirect(reverse("questions:list"))


class QuestionDetailView(PermissionRequiredMixin, LimitedQuestionMixin, DetailView):
    permission_required = 'questions.view_question'
    model = Question

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['unresolved_comment'] = self.object.comments.filter(is_resolved=False).count()
        return context


class QuestionUpdateView(PermissionRequiredMixin, SuccessMessageMixin,
                         LimitedQuestionMixin, UpdateView):
    permission_required = 'questions.change_question'
    model = Question
    form_class = QuestionForm
    success_url = reverse_lazy('questions:list')
    success_message = 'Question Updated !'


class QuestionDeleteView(PermissionRequiredMixin, LimitedQuestionMixin, DeleteView):
    permission_required = 'questions.delete_question'
    model = Question
    success_url = reverse_lazy('questions:list')


class ChoiceCreateView(PermissionRequiredMixin, SuccessMessageMixin,
                       ChoiceFormMixin, CreateView):
    permission_required = 'questions.add_choice'
    model = Choice
    fields = ('choice', 'is_correct')
    success_message = 'Choice created !'

    def form_valid(self, form):
        form.instance.question = Question(pk=self.kwargs['question'])
        form.save()
        return super().form_valid(form)


class ChoiceUpdateView(PermissionRequiredMixin, SuccessMessageMixin,
                       ChoiceFormMixin, UpdateView):
    permission_required = 'questions.change_choice'
    model = Choice
    fields = ('choice', 'is_correct')
    success_message = 'Choice Updated !'


class ChoiceDeleteView(PermissionRequiredMixin, ChoiceFormMixin, DeleteView):
    permission_required = 'questions.delete_choice'
    model = Choice

templates/questions/choice_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-12">
      <a href="#" class="btn btn-outline-primary" onclick="window.history.back()">
        <i class="fas fa-angle-left fa-xs"></i>
        Back
      </a>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
          <i class="nav-icon fas fa-edit"></i>
          {% if object %}
            <b>Update Choice</b>
          {% else %}
            <b>Create Choice</b>
          {% endif %}
      </div>
      <div class="card-body">
        <form action="." method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="row">
            <div class="col-12">
              <input class="btn btn-primary" type="submit" value="Submit">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="//cdn.ckeditor.com/4.11.4/full/ckeditor.js"></script>
<script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
{% endblock content %}

templates/questions/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row mb-3">
  <div class="col-6">
    <a href="{% url 'questions:list' %}" class="btn btn-outline-primary">
      <i class="fas fa-angle-left fa-xs"></i>
      Back
    </a>
  </div>
  <div class="col-6 text-right">
    <a
      href="#"
      onclick="document.getElementById('delete-{{ question.pk }}').submit()"
      class="btn btn-danger"
    >
        Delete
    </a>
    {% if perms.analyses.view_analysis %}
      {% if question.analysis %}
        <a href="{% url 'analyses:update' question.pk question.analysis.pk %}" class="btn btn-success">Update Analysis</a>
      {% else %}
        <a href="{% url 'analyses:create' question.pk %}" class="btn btn-success">Create Analysis</a>
      {% endif %}
    {% endif %}

    <div class="btn-group">
      <button class="btn btn-warning dropdown-toggle" type="button" data-toggle="dropdown">
        Comments
        {% if unresolved_comment %}
          <span class="badge badge-light badge-pill" style="position: static;">
            {{ unresolved_comment }}
          </span>
        {% endif %}
      </button>
      <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 35px, 0px);">
        <a class="dropdown-item" href="{% url 'comments:question_list' question.pk %}?is_resolved=false">
            Unresolved comments
            <span class="badge badge-light badge-pill" style="position: static;">
              {{ unresolved_comment }}
            </span>
        </a>
        <a class="dropdown-item" href="{% url 'comments:question_list' question.pk %}?is_resolved=unknown">All Comment</a>
        <a class="dropdown-item" href="{% url 'comments:question_create' question.pk %}">Create Comment</a>
      </div>
    </div>

    <div class="btn-group">
        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
          Action
        </button>
        <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 35px, 0px);">
          <a href="{% url 'questions:create' %}?question={{ question.pk }}" class="dropdown-item">
            Copy to new question
          </a>
          <a href="{% url 'questions:update' question.pk %}" class="dropdown-item">
            Update Question
          </a>
          <a href="{% url 'questions:choice_create' question.pk %}" class="dropdown-item">
            Add Choice
          </a>
        </div>
    </div>

  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <div class="row">
          <div class="col-12"><b>{{ question.created_by }} | {{ question.created_at }}</b></div>
        </div>
      </div>
      <div class="card-body">
        {{ question.question|safe }}
      </div>
    </div>
  </div>
</div>

{% for choice in question.choices.all %}
<div class="row mt-3">
  <div class="col-12">
    <div
      class="card {% if choice.is_correct %}card-accent-success{% endif %}"
    >
      <div class="card-header">
        <div class="row">
          <div class="col-12 text-right">
              <a
                href="{% url 'questions:choice_update' question.pk choice.pk %}"
                class="btn btn-ghost-primary"
                data-toggle="tooltip"
                data-placement="bottom"
                title="Update choice"
              >
                <i class="fas fa-pencil-alt fa-xs"></i>
              </a>
            <a href="#"
                class="btn btn-ghost-danger"
                data-toggle="tooltip"
                data-placement="bottom"
                title="Delete choice"
                onclick="document.getElementById('delete-{{ forloop.counter }}').submit()"
              >
              <i class="fas fa-trash fa-xs"></i>
            </a>
            <form
              action="{% url 'questions:choice_delete' question.pk choice.pk %}"
              id="delete-{{ forloop.counter }}"
              method="post"
                style="display:none"
            >
              {% csrf_token %}
            </form>
          </div>
        </div>
      </div>
      <div class="card-body">
        {{ choice.choice|safe }}
      </div>
    </div>
  </div>
</div>
{% endfor %}

<form
  action="{% url 'questions:delete' question.pk %}"
  id="delete-{{ question.pk }}"
  method="post"
  style="display:none"
>
  {% csrf_token %}
</form>
{% endblock content %}

templates/questions/question_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-12">
      <a
      {% if object %}
        href="{% url 'questions:detail' question.pk %}"
      {% else %}
        href="{% url 'questions:list' %}"
      {% endif %}
      class="btn btn-outline-primary"
    >
      <i class="fas fa-angle-left fa-xs"></i>
      Back
    </a>
  </div>
</div>

<form method="post">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <i class="nav-icon fas fa-edit"></i>
          {% if object %}
            <b>Update Question</b>
          {% else %}
            <b>Create Question</b>
          {% endif %}
        </div>
        <div class="card-body">
          {% csrf_token %}
          {{ form|crispy }}
          <div class="row">
            <div class="col-12">
              <input class="btn btn-primary" type="submit" value="Submit">
              {% if object %}
                <a
                  href="#"
                  onclick="document.getElementById('delete-{{ question.pk }}').submit()"
                  class="btn btn-danger"
                >
                    Delete
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if not object %}
    {{ choices.management_form }}
    {% for choice in choices %}
    <div class="row">
      <div class="col-lg-12">
          <div class="card">
              <div class="card-header">
                  <div class="card-title"><b>Choice {{ forloop.counter }}</b></div>
              </div>
              <div id="form-{{ forloop.counter }}">
                  <div class="card-body">
                    {{ choice|crispy }}
                  </div>
              </div>
          </div>
      </div>
    </div>
    {% endfor %}
  {% endif %}
</form>

{% if object %}
  <form
    action="{% url 'questions:delete' question.pk %}"
    id="delete-{{ question.pk }}"
    method="post"
    style="display:none"
  >
    {% csrf_token %}
  </form>
{% endif %}
<script src="//cdn.ckeditor.com/4.11.4/full/ckeditor.js"></script>
<script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
{% endblock content %}

templates/questions/question_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col-12 text-right">
    <a href="{% url 'questions:create' %}" class="btn btn-outline-primary">
      <i class="fas fa-plus fa-xs"></i>
      Create Question
    </a>
  </div>
</div>

<div class="row mt-3">
  <div class="col-lg-12">
    <div class="card {% if filter.form.errors %}text-white bg-danger{% endif %}">
      <div class="card-header"><b>Search Filters</b>
        <div class="card-header-actions">
          <a class="card-header-action btn-minimize" href="#" data-toggle="collapse" data-target="#collapseExample">
              <i class="nav-icon fas fa-search-plus"></i>
          </a>
        </div>
      </div>
      <div class="collapse" id="collapseExample">
        <div class="card-body">
          <form method="GET">
            {{ filter.form | crispy }}
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Search</button>
                <a href="{% url 'users:list' %}" class="btn btn-danger">Clear filters</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-2 mt-3">
    <div class="card">
      <div class="card-header">
        <b>Filter by courses</b>
      </div>
      <div class="card-body">
        {% for course in courses %}
          <a
            class="badge badge-secondary"
            href="{% url 'questions:list' %}?course__code__iexact={{ course.code }}"
          >
            {{ course.code }}
          </a>
          <br>
        {% endfor %}
        <br><br>
        <a href="{% url 'questions:list' %}" class="btn btn-outline-warning">
          clear filter
        </a>
      </div>
    </div>
  </div>
  <div class="col-10">
    {% for question in question_list %}
    <div class="card mt-3">
      <div class="card-header">
        <div class="row">
          <div class="col-6">
            <b>
              {{ question.created_by }}
              | {{ question.created_at }}
              {% if question.exam.first %}
                {# since question can be used in many exam #}
                | {{ question.exam.first.name }}
              {% endif %}
            </b>
          </div>
          <div class="col-6 text-right">
            <a href="{% url 'questions:detail' question.pk %}" class="btn btn-outline-primary">
              More
              <i class="fas fa-angle-right fa-xs"></i>
            </a>
          </div>
        </div>
      </div>
      <div class="card-body">
        {{ question.question|safe }}
        <br>
        {% for tag in question.tags.all %}
        <a
          class="badge badge-secondary"
          href="{% url 'questions:list' %}?tags__name__icontains={{ tag.name }}"
        >
          {{ tag.name }}
        </a>
        {% endfor %}
      </div>
    </div>
    {% empty %}
    <div class="clearfix text-center">
      <h4 class="pt-3">No question found</h4>
      <p class="text-muted">
        You can create one
        <a href="{% url 'questions:create' %}" class="btn-primary">here</a>
      </p>
    </div>
    {% endfor %}
  </div>
</div>

{% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1">Previous</a>
      </li>
      {% endif %}

      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" tabindex="-1">Next</a>
        </li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1">Next</a></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}
{% endblock content %}