config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views import defaults as default_views

urlpatterns = [
    path('', include('questionbank.dashboards.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('questionbank.users.urls')),
    path('invites/', include('questionbank.invites.urls')),
    path('subjects/', include('questionbank.subjects.urls')),
    path('questions/', include('questionbank.questions.urls')),
    path('exams/', include('questionbank.exams.urls')),
    path('comments/', include('questionbank.comments.urls')),
    path('analysis/', include('questionbank.analyses.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += [
        path(
            '400/', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]

questionbank/exams/urls.py
from django.urls import path

from .views import (
    ExamListView, ExamCreateView, ExamUpdateView, ExamQuestionView,
    ExamDeleteView, ExamPrintView
)


app_name = 'exams'
urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('create/', ExamCreateView.as_view(), name='create'),
    path('<int:pk>/update/', ExamUpdateView.as_view(), name='update'),
    path('<int:pk>/add-question/', ExamQuestionView.as_view(), name='add_question'),
    path('<int:pk>/delete/', ExamDeleteView.as_view(), name='delete'),
    path('<int:pk>/print/', ExamPrintView.as_view(), name='print')
]

questionbank/invites/urls.py
from django.urls import path

from .views import InviteCreateView, InviteListView, InviteDeleteView


app_name = 'invites'
urlpatterns = [
    path('', InviteListView.as_view(), name='list'),
    path('create/', InviteCreateView.as_view(), name='create'),
    path('<int:pk>/', InviteDeleteView.as_view(), name='delete')
]

questionbank/subjects/urls.py
from django.urls import path

from .views import (
    SubjectListView, SubjectCreateView, SubjectUpdateView, SubjectDeleteView
)

app_name = 'subjects'
urlpatterns = [
    path('', SubjectListView.as_view(), name='list'),
    path('create/', SubjectCreateView.as_view(), name='create'),
    path('<int:pk>/update/', SubjectUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', SubjectDeleteView.as_view(), name='delete')
]

questionbank/users/urls.py
from django.urls import path

from .views import (
    UserListView, UserUpdateView, UserProfileView, UserDeleteView,
    AcceptInvitationView, SpecialtyListView, SpecialtyCreateView, SpecialtyUpdateView,
    SpecialtyDeleteView
)


app_name = 'users'
urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('<int:pk>/', UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', UserDeleteView.as_view(), name='delete'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path(
        'invite/<str:token>/', AcceptInvitationView.as_view(),
        name='accept_invite'
    ),
    path('specialties/', SpecialtyListView.as_view(), name='specialty_list'),
    path('specialties/create/', SpecialtyCreateView.as_view(), name='specialty_create'),
    path('specialties/<int:pk>/update/', SpecialtyUpdateView.as_view(), name='specialty_update'),
    path('specialties/<int:pk>/delete/', SpecialtyDeleteView.as_view(), name='specialty_delete')
]

templates/base.html
{% load render_bundle from webpack_loader %}
{% load cache %}
{% cache 86400 basepagetop %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Qbank</title>
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed sidebar-lg-show">
  {% render_bundle 'runtime' %}
  {% render_bundle 'main' %}
  {% render_bundle 'vendor' %}
  {% render_bundle 'main_css' %}
{% endcache %}
  {% include 'header.html' %}

  <div class="app-body">
    {% include "sidebar.html" %}
    <main class="main">
      <div class="container-fluid my-4">
        {% block content %}{% endblock %}
      </div>
    </main>
  </div>

  {% if messages %}
      {% for message in messages %}
        <script>
          toastr.options = {
            "closeButton": true,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-bottom-right",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
          }
          toastr['{{ message.tags }}']('{{ message }}')
        </script>
      {% endfor %}
  {% endif %}
</body>
</html>

templates/header.html
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="/">
    <img class="navbar-brand-full" src="#" width="89" height="25" alt="Qbank">
    <img class="navbar-brand-minimized" src="#" width="30" height="30" alt="Qbank">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
      <a class="nav-link" href="/">Dashboard</a>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="{% url 'users:profile' %}">Profile</a>
    </li>
  </ul>

  <ul class="nav navbar-nav ml-auto" style="margin-right: 3%">
    <li class="nav-item dropdown">
      <a class="nav-link nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        {{ request.user.username|title }} <i class="fas fa-caret-down fa-xs"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{% url 'account_logout' %}"><i class="fa fa-lock"></i> Logout</a>
      </div>
    </li>
  </ul>

</header>

templates/sidebar.html
<div class="sidebar">
  <nav class="sidebar-nav">
    <ul class="nav">

      {% if perms.subjects.view_subjects %}
      <li class="nav-item">
        <a href="{% url 'subjects:list' %}" class="nav-link">
          <i class="nav-icon fas fa-book-medical"></i> Courses
        </a>
      </li>
      {% endif %}

      {% if perms.questions.view_question %}
      <li class="nav-item">
        <a href="{% url 'questions:list' %}" class="nav-link">
          <i class="nav-icon fas fa-edit"></i> Questions
        </a>
      </li>
      {% endif %}

      {% if perms.exams.view_exam %}
      <li class="nav-item">
        <a href="{% url 'exams:list' %}" class="nav-link">
          <i class="nav-icon fas fa-scroll"></i> Exams
        </a>
      </li>
      {% endif %}

      {% if request.user.is_superuser %}
      <li class="nav-item">
        <a href="{% url 'users:list' %}" class="nav-link">
          <i class="nav-icon fas fa-users"></i>
          User Management
        </a>
      </li>
      {% endif %}

      {% if request.user.is_superuser %}
      <li class="nav-item">
        <a href="{% url 'invites:list' %}" class="nav-link">
          <i class="nav-icon fas fa-list"></i>
          Invitations
        </a>
      </li>
      {% endif %}

      {% if request.user.is_superuser %}
      <li class="nav-item">
        <a href="{% url 'users:specialty_list' %}" class="nav-link">
          <i class="nav-icon fas fa-bolt"></i>
          Specialties
        </a>
      </li>
      {% endif %}

    </ul>
  </nav>
</div>