config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views import defaults as default_views

urlpatterns = [
    path('', include('questionbank.dashboards.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('questionbank.users.urls')),
    path('invites/', include('questionbank.invites.urls')),
    path('subjects/', include('questionbank.subjects.urls')),
    path('questions/', include('questionbank.questions.urls')),
    path('exams/', include('questionbank.exams.urls')),
    path('comments/', include('questionbank.comments.urls')),
    path('analysis/', include('questionbank.analyses.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))
    ] + urlpatterns

    urlpatterns += [
        path(
            '400/', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')},
        ),
        path(
            '403/', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')},
        ),
        path(
            '404/', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')},
        ),
        path('500/', default_views.server_error),
    ]

questionbank/comments/urls.py
from django.urls import path

from .views import (
    ExamCommentListView, ExamCommentCreateView, ExamCommentUpdateView,
    ExamCommentDeleteView, ExamCommentResolveView, QuestionCommentListView,
    QuestionCommentCreateView, QuestionCommentUpdateView,
    QuestionCommentDeleteView, QuestionCommentResolveView
)

app_name = 'comments'
urlpatterns = [
    path('exams/<int:exam_id>/', ExamCommentListView.as_view(), name='exam_list'),
    path(
        'exams/<int:exam_id>/create/',
        ExamCommentCreateView.as_view(),
        name='exam_create'
    ),
    path(
        'exams/<int:exam_id>/update/<int:pk>/',
        ExamCommentUpdateView.as_view(),
        name='exam_update'
    ),
    path(
        'exams/<int:exam_id>/delete/<int:pk>/',
        ExamCommentDeleteView.as_view(),
        name='exam_delete'
    ),
    path(
        'exams/<int:exam_id>/resolve/<int:pk>/',
        ExamCommentResolveView.as_view(),
        name='exam_resolve'
    ),

    path(
        'questions/<int:question_id>/',
        QuestionCommentListView.as_view(),
        name='question_list'
    ),
    path(
        'questions/<int:question_id>/create/',
        QuestionCommentCreateView.as_view(),
        name='question_create'
    ),
    path(
        'questions/<int:question_id>/update/<int:pk>/',
        QuestionCommentUpdateView.as_view(),
        name='question_update'
    ),
    path(
        'questions/<int:question_id>/delete/<int:pk>/',
        QuestionCommentDeleteView.as_view(),
        name='question_delete'
    ),
    path(
        'questions/<int:question_id>/resolve/<int:pk>/',
        QuestionCommentResolveView.as_view(),
        name='question_resolve'
    )
]

questionbank/exams/urls.py
from django.urls import path

from .views import (
    ExamListView, ExamCreateView, ExamUpdateView, ExamQuestionView,
    ExamDeleteView, ExamPrintView
)


app_name = 'exams'
urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('create/', ExamCreateView.as_view(), name='create'),
    path('<int:pk>/update/', ExamUpdateView.as_view(), name='update'),
    path('<int:pk>/add-question/', ExamQuestionView.as_view(), name='add_question'),
    path('<int:pk>/delete/', ExamDeleteView.as_view(), name='delete'),
    path('<int:pk>/print/', ExamPrintView.as_view(), name='print')
]

questionbank/questions/urls.py
from django.urls import path

from .views import (
    QuestionListView, QuestionCreateView, QuestionUpdateView,
    QuestionDetailView, QuestionDeleteView, ChoiceCreateView,
    ChoiceUpdateView, ChoiceDeleteView
)

app_name = 'questions'
urlpatterns = [
    path('', QuestionListView.as_view(), name='list'),
    path('create/', QuestionCreateView.as_view(), name='create'),
    path('<int:pk>/detail/', QuestionDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', QuestionUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', QuestionDeleteView.as_view(), name='delete'),

    path(
        '<int:question>/choices/create/', ChoiceCreateView.as_view(),
        name='choice_create'
    ),
    path(
        '<int:question>/choices/<int:pk>/update/', ChoiceUpdateView.as_view(),
        name='choice_update'
    ),
    path(
        '<int:question>/choices/<int:pk>/delete/', ChoiceDeleteView.as_view(),
        name='choice_delete'
    )

]

questionbank/comments/models.py
from django.db import models
from django.contrib.auth import get_user_model

from questionbank.questions.models import Question
from questionbank.exams.models import Exam

User = get_user_model()


class BaseComment(models.Model):
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    is_resolved = models.BooleanField(default=False, verbose_name='resolved')

    class Meta:
        abstract = True


class QuestionComment(BaseComment):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE,
        related_name='comments'
    )


class ExamComment(BaseComment):
    exam = models.ForeignKey(
        Exam, on_delete=models.CASCADE,
        related_name='comments'
    )

questionbank/comments/views.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django_filters.views import FilterView

from questionbank.exams.models import Exam
from questionbank.questions.models import Question

from .filters import ExamCommentFilter, QuestionCommentFilter
from .models import ExamComment, QuestionComment
from .mixins import (
    ExamSuccessUrlMixin, ExamContextDataMixin,
    QuestionSuccessUrlMixin, QuestionContextDataMixin
)


class ExamCommentListView(PermissionRequiredMixin, ExamContextDataMixin, FilterView):
    permission_required = 'comments.view_examcomment'
    model = ExamComment
    filterset_class = ExamCommentFilter
    template_name_suffix = '_list'
    paginate_by = 20

    def get_queryset(self):
        return ExamComment.objects.filter(
            exam_id=self.kwargs['exam_id']
        ).order_by('-created_at').prefetch_related('created_by')


class ExamCommentCreateView(PermissionRequiredMixin, SuccessMessageMixin,
                            ExamSuccessUrlMixin, CreateView):
    permission_required = 'comments.add_examcomment'
    model = ExamComment
    fields = ('comment',)
    success_message = 'Comment created'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.exam = Exam(pk=self.kwargs['exam_id'])
        self.object = form.save()

        self.object.refresh_from_db()
        send_mail(
            subject=f'{self.request.user.username} commented on exam {self.kwargs["exam_id"]}',
            message=f'{self.object.comment} <br /> {self.object.exam.get_absolute_url()}',
            from_email='medicputraqbank@example.com',
            recipient_list=[self.object.exam.created_by.email],
        )

        return super().form_valid(form)


class ExamCommentUpdateView(PermissionRequiredMixin, SuccessMessageMixin,
                            ExamSuccessUrlMixin, UpdateView):
    permission_required = 'comments.change_examcomment'
    model = ExamComment
    fields = ('comment', 'is_resolved')
    success_message = 'Comment updated'

    def get_queryset(self):
        return ExamComment.objects.filter(
            created_by=self.request.user
        )


class ExamCommentResolveView(PermissionRequiredMixin, ExamSuccessUrlMixin,
                             UpdateView):
    permission_required = 'comments.change_examcomment'
    model = ExamComment
    fields = ('is_resolved',)

    def get_queryset(self):
        return QuestionComment.objects.filter(
            exam__created_by=self.request.user
        )

    def form_valid(self, form):
        form.instance.is_resolved = True
        self.object = form.save()

        send_mail(
            subject=f'{self.request.user.username} resolved your comment on exam {self.kwargs["exam_id"]}',
            message=f'{self.object.comment} <br /> {self.object.exam.get_absolute_url()}',
            from_email='medicputraqbank@example.com',
            recipient_list=[self.object.created_by.email],
        )

        return super().form_valid(form)


class ExamCommentDeleteView(PermissionRequiredMixin, ExamSuccessUrlMixin, DeleteView):
    permission_required = 'comments.delete_examcomment'
    model = ExamComment


class QuestionCommentListView(PermissionRequiredMixin, QuestionContextDataMixin,
                              FilterView):
    permission_required = 'comments.view_questioncomment'
    module = QuestionComment
    filterset_class = QuestionCommentFilter
    template_name_suffix = '_list'
    paginate_by = 20

    def get_queryset(self):
        return QuestionComment.objects.filter(
            question=self.kwargs['question_id']
        ).order_by('-created_at').prefetch_related('created_by')


class QuestionCommentCreateView(PermissionRequiredMixin, SuccessMessageMixin,
                                QuestionSuccessUrlMixin, CreateView):
    permission_required = 'comments.add_questioncomment'
    model = QuestionComment
    fields = ('comment',)
    success_message = 'Comment created'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.question = Question(pk=self.kwargs['question_id'])
        self.object = form.save()

        self.object.refresh_from_db()
        send_mail(
            subject=f'{self.request.user.username} commented on question {self.kwargs["question_id"]}',
            message=f'{self.object.comment} <br /> {self.object.question.get_absolute_url()}',
            from_email='medicputraqbank@example.com',
            recipient_list=[self.object.question.created_by.email],
        )

        return super().form_valid(form)


class QuestionCommentUpdateView(PermissionRequiredMixin, SuccessMessageMixin,
                                QuestionSuccessUrlMixin, UpdateView):
    permission_required = 'comments.change_questioncomment'
    model = QuestionComment
    fields = ('comment', 'is_resolved')
    success_message = 'Comment updated'

    def get_queryset(self):
        return QuestionComment.objects.filter(
            created_by=self.request.user
        )


class QuestionCommentResolveView(PermissionRequiredMixin, QuestionSuccessUrlMixin,
                                 UpdateView):
    permission_required = 'comments.change_questioncomment'
    model = QuestionComment
    fields = ('is_resolved',)

    def get_queryset(self):
        return QuestionComment.objects.filter(
            question__created_by=self.request.user
        )

    def form_valid(self, form):
        form.instance.is_resolved = True
        self.object = form.save()

        send_mail(
            subject=f'{self.request.user.username} resolved your comment on question {self.kwargs["question_id"]}',
            message=f'{self.object.comment} <br /> {self.object.question.get_absolute_url()}',
            from_email='medicputraqbank@example.com',
            recipient_list=[self.object.created_by.email],
        )

        return super().form_valid(form)


class QuestionCommentDeleteView(PermissionRequiredMixin, QuestionSuccessUrlMixin,
                                DeleteView):
    permission_required = 'comments.delete_questioncomment'
    model = QuestionComment

templates/comments/examcomment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-12">
      <a href="{% url 'comments:exam_list' exam_id %}" class="btn btn-outline-primary">
        <i class="fas fa-angle-left fa-xs"></i>
        Back
      </a>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <i class="nav-icon fas fa-comment"></i>
        {% if object %}
          Update Comment
        {% else %}
          Add Comment
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/comments/examcomment_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-6">
      <a href="{% url 'exams:update' exam_id %}" class="btn btn-outline-primary">
        <i class="fas fa-angle-left fa-xs"></i>
        Back
      </a>
  </div>
  <div class="col-6 text-right">
    <a href="{% url 'comments:exam_create' exam_id %}" class="btn btn-outline-primary">
      <i class="fas fa-plus fa-xs"></i>
      Create Comment
    </a>
  </div>
</div>

<div class="row mt-3 mb-3">
  <div class="col-lg-12">
    <div class="btn-group" role="group" aria-label="Basic example">
      <a
        href="{% url 'comments:exam_list' exam_id %}?is_resolved=false"
        class="btn {% if filter.data.is_resolved == 'false' %}btn-secondary{% endif %}"
      >
        Unresolved
      </a>
      <a
        href="{% url 'comments:exam_list' exam_id %}?is_resolved=true"
        class="btn {% if filter.data.is_resolved == 'true' %}btn-secondary{% endif %}"
      >
        Resolved
      </a>
      <a
        href="{% url 'comments:exam_list' exam_id %}?is_resolved=unknown"
        class="btn {% if filter.data.is_resolved == 'unknown' %}btn-secondary{% endif %}"
      >
        All
      </a>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    {% if object_list %}
      {% for comment in examcomment_list %}
        <div class="card mb-3">
          <div class="card-header">
            <div class="row">
              <div class="col-6">
                <i class="nav-icon fas fa-comment"></i>
                <b>{{ comment.created_by }}</b> | {{ comment.created_at }}
              </div>
              <div class="col-6 text-right">
                {% if comment.created_by == request.user %}
                  <a
                    href="{% url 'comments:exam_update' exam_id comment.pk %}"
                    class="btn btn-ghost-primary"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="Update choice"
                  >
                    <i class="fas fa-pencil-alt fa-xs"></i>
                  </a>
                  <a href="#"
                      class="btn btn-ghost-danger"
                      data-toggle="tooltip"
                      data-placement="bottom"
                      title="Delete choice"
                      onclick="document.getElementById('delete-{{ forloop.counter }}').submit()"
                    >
                    <i class="fas fa-trash fa-xs"></i>
                  </a>
                  <form
                    action="{% url 'comments:exam_delete' exam_id comment.pk %}"
                    id="delete-{{ forloop.counter }}"
                    method="post"
                    style="display:none"
                  >
                    {% csrf_token %}
                  </form>
                {% endif %}
                {% if not comment.is_resolved %}
                  <a
                    href="#"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="Mark as resolved"
                    class="btn btn-ghost-success"
                    onclick="document.getElementById('resolve-{{ forloop.counter }}').submit()"
                  >
                    <i class="fas fa-check fa-xs"></i>
                  </a>
                  <form
                    action="{% url 'comments:exam_resolve' exam_id comment.pk %}"
                    id="resolve-{{ forloop.counter }}"
                    method="post"
                    style="display:none"
                  >
                    {% csrf_token %}
                    {{ form }}
                  </form>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="card-body">
            {{ comment.comment }}
          </div>
        </div>
      {% endfor %}
    {% else %}
    <div class="card">
      <div class="card-body">
        <div class="clearfix text-center">
          <h4 class="pt-3">No comment found</h4>
          <p class="text-muted">
            You can create one
            <a href="{% url 'comments:exam_create' exam_id %}" class="btn-primary">
              here
            </a>
          </p>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

templates/comments/questioncomment_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row mb-3">
  <div class="col-12">
      <a
        {% if exam_id %}
          href="{% url 'exams:update' exam_id %}"
        {% else %}
          href="{% url 'comments:question_list' question_id %}"
        {% endif %}
        class="btn btn-outline-primary"
      >
        <i class="fas fa-angle-left fa-xs"></i>
        Back
      </a>
  </div>
</div>

<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <i class="nav-icon fas fa-comment"></i>
        {% if object %}
          Update Comment
        {% else %}
          Add Comment
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form|crispy }}
          <input type="submit" value="submit" class="btn btn-primary">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/comments/questioncomment_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col-6">
      <a
        {% if exam_id %}
          href="{% url 'exams:update' exam_id %}"
        {% else %}
          href="{% url 'questions:detail' question_id %}"
        {% endif %}
        class="btn btn-outline-primary"
      >
        <i class="fas fa-angle-left fa-xs"></i>
        Back
      </a>
  </div>
  <div class="col-6 text-right">
    <a
      {% if exam_id %}
      href="{% url 'comments:question_create' question_id %}?exam={{ exam_id }}"
      {% else %}
        href="{% url 'comments:question_create' question_id %}"
      {% endif %}
      class="btn btn-outline-primary"
    >
      <i class="fas fa-plus fa-xs"></i>
      Create Comment
    </a>
  </div>
</div>

<div class="row mt-3 mb-3">
  <div class="col-lg-12">
    <div class="btn-group" role="group" aria-label="Basic example">
      <a
        {% if exam_id %}
          href="{% url 'comments:question_list' question_id %}?is_resolved=false&exam={{ exam_id }}"
        {% else %}
          href="{% url 'comments:question_list' question_id %}?is_resolved=false"
        {% endif %}
        class="btn {% if filter.data.is_resolved == 'false' %}btn-secondary{% endif %}"
      >
        Unresolved
      </a>
      <a
        {% if exam_id %}
          href="{% url 'comments:question_list' question_id %}?is_resolved=true&exam={{ exam_id }}"
        {% else %}
          href="{% url 'comments:question_list' question_id %}?is_resolved=true"
        {% endif %}
        class="btn {% if filter.data.is_resolved == 'true' %}btn-secondary{% endif %}"
      >
        Resolved
      </a>
      <a
        {% if exam_id %}
          href="{% url 'comments:question_list' question_id %}?is_resolved=unknown&exam={{ exam_id }}"
        {% else %}
          href="{% url 'comments:question_list' question_id %}?is_resolved=unknown"
        {% endif %}
        class="btn {% if filter.data.is_resolved == 'unknown' %}btn-secondary{% endif %}"
      >
        All
      </a>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-12">
    {% if object_list %}
      {% for comment in questioncomment_list %}
        <div class="card mb-3">
          <div class="card-header">
            <div class="row">
              <div class="col-6">
                <i class="nav-icon fas fa-comment"></i>
                <b>{{ comment.created_by }}</b> | {{ comment.created_at }}
              </div>
              <div class="col-6 text-right">
                {% if comment.created_by == request.user %}
                  <a
                    href="{% url 'comments:question_update' question_id comment.pk %}"
                    class="btn btn-ghost-primary"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="Update comment"
                  >
                    <i class="fas fa-pencil-alt fa-xs"></i>
                  </a>
                  <a href="#"
                      class="btn btn-ghost-danger"
                      data-toggle="tooltip"
                      data-placement="bottom"
                      title="Delete comment"
                      onclick="document.getElementById('delete-{{ forloop.counter }}').submit()"
                    >
                    <i class="fas fa-trash fa-xs"></i>
                  </a>
                  <form
                    action="{% url 'comments:question_delete' question_id comment.pk %}"
                    id="delete-{{ forloop.counter }}"
                    method="post"
                    style="display:none"
                  >
                    {% csrf_token %}
                  </form>
                {% endif %}
                {% if not comment.is_resolved %}
                  <a
                    href="#"
                    data-toggle="tooltip"
                    data-placement="bottom"
                    title="Mark as resolved"
                    class="btn btn-ghost-success"
                    onclick="document.getElementById('resolve-{{ forloop.counter }}').submit()"
                  >
                    <i class="fas fa-check fa-xs"></i>
                  </a>
                  <form
                    action="{% url 'comments:question_resolve' question_id comment.pk %}"
                    id="resolve-{{ forloop.counter }}"
                    method="post"
                    style="display:none"
                  >
                    {% csrf_token %}
                    {{ form }}
                  </form>
                {% endif %}
              </div>
            </div>
          </div>
          <div class="card-body">
            {{ comment.comment }}
          </div>
        </div>
      {% endfor %}
    {% else %}
    <div class="card">
      <div class="card-body">
        <div class="clearfix text-center">
          <h4 class="pt-3">No comment found</h4>
          <p class="text-muted">
            You can create one
            <a href="{% url 'comments:question_create' question_id %}" class="btn-primary">
              here
            </a>
          </p>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}